networks:
  dome-network:
services:
  # Databases
  redis:
    container_name: redis
    image: redis:7.0.0
    command: >
      --requirepass ${REDIS_PASSWORD}
    networks:
      - dome-network
    ports:
      - 6379:6379
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    image: postgres:14.3-alpine
    networks:
      - dome-network
    ports:
      - 5432:5432
  # Services
  depot:
    container_name: depot
    depends_on:
      - postgres
    image: domenetwork/depot:dev
    networks:
      - dome-network
    ports:
      - 5002:5002
    volumes:
      - ./:/app/config
  nym:
    container_name: nym
    depends_on:
      - postgres
      - redis
    image: domenetwork/nym:dev
    networks:
      - dome-network
    ports:
      - 5001:5001
    volumes:
      - ./:/app/config
